mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
]

shop/urls.py
from django.urls import path
from .views import greetings, ListItem, DetailItem

urlpatterns = [
    path('shop/greetings', greetings, name='greetings'),
    path('shop/', ListItem.as_view(), name='list_item'),
    path('shop/<int:pk>', DetailItem.as_view(), name='detail_item')
]

shop/models.py
from django.db import models

class Item(models.Model):
    name = models.CharField(max_length=30)
    price = models.IntegerField()

    def __str__(self):
        return self.name

class Purchase(models.Model):
    name = models.CharField(max_length=30)
    age = models.IntegerField()
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    purchase_date = models.DateField('date purchase')

    def __str__(self):
        return self.name

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import  HttpResponse
from .models import Item, Purchase
from django.views import generic

def greetings(request):
    return HttpResponse("Добро пожаловать в наш магазин!")


# def list_item(request):
#     items= Item.objects.all()
#     contex = {
#         'items':items,
#     }
#     return render(request, 'list_item.html', contex)
class ListItem(generic.ListView):
    model = Item
    template_name = 'list_item.html'
    context_object_name = 'items'

# def detail_item(request, item_id):
#     item = get_object_or_404(Item, id=item_id)
#     #item = Item.objects.get(id=item_id)
#     contex = {
#         'item':item,
#     }
#     return render(request, 'detail_item.html', contex)


class DetailItem(generic.DetailView):
    model = Item
    template_name = 'detail_item.html'
    context_object_name = 'item'

shop/templates/detail_item.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<h1>{{item.name}}</h1>

<form method="POST">
    {% csrf_token %}
    {% for purchase in item.purchase_set.all %}
       <li> Имя покупателя: {{ purchase.name }} - {{ purchase.age }} лет, - дата покупки {{ purchase.purchase_date}}</li>
    {% endfor %}


</form>


</body>
</html>

shop/templates/list_item.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

    <ul>
        {% for item in items %}

            <li><a href="{% url 'detail_item' item.id %}">{{ item.id }} - {{ item.name }} - $ {{ item.price }}</a></li>

        {% endfor %}
    </ul>

</body>
</html>